import { useEffect, useRef, useState } from 'react';
import { Icon } from './chrome/Icon';
import { AttendeeChips } from './AttendeeChips';
import { TagChips } from './TagChips';
import { TemplateMultiPicker } from './TemplateMultiPicker';
import { api } from '../api/client';
import type { Recording, RecordingLink, RecordingAttachment, MeetingTemplate } from '../types';

/** Editable context for a recording: template, name, attendees, notes, links, document
 *  attachments, and a "Save to Knowledge Hub" toggle. Text edits debounce-PATCH;
 *  toggles/attachments are immediate. Used both in the live recording view and the
 *  Recordings detail. The template picker only renders when `templates` is supplied —
 *  the Recordings detail passes none, since the outputs are already generated by then. */
export function RecordingContextPanel({ rec, onChange, compact, templates, onTemplatesChanged, hideKnowledgeToggle, hideNotes }: {
  rec: Recording;
  onChange?: (r: Recording) => void;
  compact?: boolean;
  templates?: MeetingTemplate[];
  onTemplatesChanged?: () => void;
  /** Live recording view owns this as a header checkbox — hide the panel's own toggle. */
  hideKnowledgeToggle?: boolean;
  /** Live recording view owns notes in the centre column, beneath the pin composer, so the
   *  same string isn't editable in two boxes at once (this panel only re-seeds on rec.id, so
   *  a second editor would show stale text as notes are pinned). */
  hideNotes?: boolean;
}) {
  const [name, setName] = useState(rec.name);
  const [notes, setNotes] = useState(rec.notes ?? '');
  const [links, setLinks] = useState<RecordingLink[]>(rec.links ?? []);
  const [atts, setAtts] = useState<RecordingAttachment[]>(rec.attachments ?? []);
  const [toKnowledge, setToKnowledge] = useState(rec.saveToKnowledge ?? true);
  const [linkUrl, setLinkUrl] = useState('');
  const [uploading, setUploading] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const debRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Re-seed when the recording changes (switching rows / poll updates).
  useEffect(() => {
    setName(rec.name); setNotes(rec.notes ?? ''); setLinks(rec.links ?? []);
    setAtts(rec.attachments ?? []); setToKnowledge(rec.saveToKnowledge ?? true);
  }, [rec.id]); // eslint-disable-line react-hooks/exhaustive-deps

  const patch = (p: Partial<Recording>) => api.updateRecording(rec.id, p).then((r) => onChange?.(r)).catch(() => {});
  const debouncedPatch = (p: Partial<Recording>) => {
    if (debRef.current) clearTimeout(debRef.current);
    debRef.current = setTimeout(() => patch(p), 500);
  };

  const addLink = () => {
    const url = linkUrl.trim();
    if (!url) return;
    const next = [...links, { url }];
    setLinks(next); setLinkUrl(''); patch({ links: next });
  };
  const removeLink = (i: number) => { const next = links.filter((_, j) => j !== i); setLinks(next); patch({ links: next }); };

  const onFiles = async (files: FileList | null) => {
    if (!files?.length) return;
    setUploading(true);
    for (const f of Array.from(files)) {
      try { const att = await api.attachToRecording(rec.id, f); setAtts((prev) => [...prev, att]); }
      catch { /* skip */ }
    }
    setUploading(false);
    if (fileRef.current) fileRef.current.value = '';
    api.getRecording(rec.id).then((r) => onChange?.(r)).catch(() => {});
  };
  const removeAtt = async (n: string) => {
    setAtts((prev) => prev.filter((a) => a.name !== n));
    await api.removeRecordingAttachment(rec.id, n).then((r) => onChange?.(r)).catch(() => {});
  };

  const inputCls = 'w-full rounded-[8px] border border-border bg-bg text-ink text-[13px] outline-none focus:border-accent';

  return (
    <div className="flex flex-col gap-3">
      {!compact && (
        <Label text="Name">
          <input value={name} onChange={(e) => { setName(e.target.value); debouncedPatch({ name: e.target.value }); }}
            onBlur={() => patch({ name })} placeholder="Recording name" className={`${inputCls} h-9 px-2.5`} />
        </Label>
      )}

      {templates && templates.length > 0 && (
        <Label text="Template" hint="What kind of meeting this is — decides the copilot's live focus and the outputs you get.">
          <TemplateMultiPicker
            templates={templates}
            value={rec.templateIds ?? (rec.templateId ? [rec.templateId] : [])}
            onChange={(ids) => patch({ templateIds: ids })}
            onTemplatesChanged={onTemplatesChanged ?? (() => {})}
          />
        </Label>
      )}

      <Label text="Attendees" hint="Who's in the meeting — sharpens transcription and lets the copilot attribute action items. Click a person icon to mark the organizer.">
        <AttendeeChips
          value={rec.attendees ?? []}
          onChange={(names) => patch({ attendees: names })}
          organizer={rec.organizer ?? null}
          onOrganizerChange={(name) => patch({ organizer: name })}
        />
      </Label>

      <Label text="Tags" hint="Group and find this recording later. The first tag decides which group it files under.">
        <TagChips value={rec.tags ?? []} onChange={(tags) => patch({ tags })} />
      </Label>

      {!hideNotes && (
        <Label text="Notes" hint="Context for the copilot & agents — what this is, decisions, anything off-mic.">
          <textarea value={notes} onChange={(e) => { setNotes(e.target.value); debouncedPatch({ notes: e.target.value }); }}
            onBlur={() => patch({ notes })} rows={compact ? 3 : 4} placeholder="Add notes…"
            className={`${inputCls} px-2.5 py-2 resize-y leading-relaxed`} />
        </Label>
      )}

      <Label text="Links">
        <div className="flex flex-col gap-1.5">
          {links.map((l, i) => (
            <div key={i} className="group flex items-center gap-2 px-2.5 py-1.5 rounded-[8px] bg-bg border border-border">
              <Icon name="library" size={12} color="var(--color-ink3)" />
              <a href={l.url} target="_blank" rel="noreferrer" className="flex-1 text-[12.5px] text-accent-dark truncate hover:underline">{l.title || l.url}</a>
              <button type="button" title="Remove" onClick={() => removeLink(i)} className="text-ink3 opacity-0 group-hover:opacity-100 hover:text-rec"><Icon name="x" size={12} /></button>
            </div>
          ))}
          <div className="flex items-center gap-1.5">
            <input value={linkUrl} onChange={(e) => setLinkUrl(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && addLink()}
              placeholder="https://…" className={`${inputCls} h-8 px-2.5 text-[12.5px]`} />
            <button type="button" onClick={addLink} disabled={!linkUrl.trim()}
              className="h-8 px-2.5 rounded-[8px] border border-border bg-card text-ink2 text-[12px] hover:border-ink3 disabled:opacity-40 flex-none">Add</button>
          </div>
        </div>
      </Label>

      <Label text="Documents" hint="Attached files are read (as text) into the summarizer & agent context.">
        <div className="flex flex-col gap-1.5">
          {atts.map((a) => (
            <div key={a.name} className="group flex items-center gap-2 px-2.5 py-1.5 rounded-[8px] bg-bg border border-border">
              <Icon name="file" size={12} color="var(--color-ink3)" />
              <span className="flex-1 text-[12.5px] text-ink2 truncate">{a.name}</span>
              {a.chars != null && <span className="font-mono text-[10px] text-ink3 flex-none">{a.chars > 999 ? `${Math.round(a.chars / 1000)}k` : a.chars} chars</span>}
              <button type="button" title="Remove" onClick={() => removeAtt(a.name)} className="text-ink3 opacity-0 group-hover:opacity-100 hover:text-rec"><Icon name="x" size={12} /></button>
            </div>
          ))}
          <input ref={fileRef} type="file" multiple aria-label="Attach document" className="hidden" onChange={(e) => onFiles(e.target.files)} />
          <button type="button" onClick={() => fileRef.current?.click()} disabled={uploading}
            className="h-8 px-2.5 rounded-[8px] border border-dashed border-border text-ink3 text-[12px] hover:border-ink3 flex items-center justify-center gap-1.5 disabled:opacity-60">
            <Icon name="paperclip" size={13} /> {uploading ? 'Uploading…' : 'Attach document'}
          </button>
        </div>
      </Label>

      {!hideKnowledgeToggle && (
        <button type="button" onClick={() => { const v = !toKnowledge; setToKnowledge(v); patch({ saveToKnowledge: v }); }}
          className="flex items-center gap-2.5 px-3 py-2 rounded-[10px] border border-border bg-card text-left hover:border-ink3">
          <span className={`relative w-[34px] h-[20px] rounded-full flex-none transition-colors ${toKnowledge ? 'bg-accent' : 'bg-border'}`}>
            <span className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-all ${toKnowledge ? 'left-[16px]' : 'left-0.5'}`} />
          </span>
          <span className="flex-1">
            <span className="block text-[12.5px] text-ink font-500">Save to Knowledge Hub</span>
            <span className="block text-[11px] text-ink3">File this meeting into long-term knowledge.</span>
          </span>
        </button>
      )}
    </div>
  );
}

function Label({ text, hint, children }: { text: string; hint?: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="text-[11px] uppercase tracking-wider text-ink3 font-600 mb-1">{text}</div>
      {hint && <div className="text-[11px] text-ink3 mb-1.5 -mt-0.5 normal-case tracking-normal font-400">{hint}</div>}
      {children}
    </div>
  );
}
